# Important Notes:
# Every field you add must be added to the root build.gradle expandProps map.

# Project
version=1.3.0
group=org.dawnoftime.armoroftheages
java_version=21

# Minecraft
minecraft_version=1.20.6

# Common
mod_name=Armor of the Ages
mod_author=Poulpinou
mod_id=armoroftheages
license=MIT
credits=TheGoldenWorld, Mr_ch0c0late, Hahdrim
description=A mod that adds fancy armors from different cultures.
minecraft_version_range=[1.20.6, 1.21)

# Fabric
fabric_version=0.99.0+1.20.6
fabric_loader_version=0.15.11

# NeoForge
neoforge_version=20.6.84-beta
neoforge_loader_version_range=[2,)

# Gradle
org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false
