# Important Notes:
# fabric.mod.json's modid field cannot be expanded, you must change it manually.
# Every field you add must be added to the root build.gradle expandProps map.

# Project
version=1.5.9
group=org.dawnoftime.armoroftheages
java_version=21

# Common
minecraft_version=1.21.1
# The version of ParchmentMC that is used, see https://parchmentmc.org/docs/getting-started#choose-a-version for new versions
parchment_minecraft=1.21.1
parchment_version=2024.11.17
# NeoForge

neoforge_version=21.1.197
neoforge_loader_version_range=[4,)
neo_form_version=1.21.1-20240808.144430

minecraft_version_range=[1.21.1]

# Fabric
fabric_version=0.116.4+1.21.1
fabric_loader_version=0.16.14

# Configuration
yacl_version=3.7.1+1.21.1

# Mod options
mod_name=Armor of the Ages
mod_author=Poulpinou
credits=TheGoldenWorld, Mr_ch0c0late, Hahdrim
mod_id=armoroftheages
license=MIT
description=A mod that adds fancy armors from different cultures.

# Gradle
org.gradle.jvmargs=-Xmx8G
org.gradle.daemon=false