# Important Notes:
# Every field you add must be added to the root build.gradle expandProps map.

# Project
version=1.5.4
group=org.dawnoftime.armoroftheages
java_version=21

# Common
minecraft_version=1.21.1
mod_name=Armor of the Ages
mod_author=Poulpinou
mod_id=armoroftheages
license=MIT
credits=TheGoldenWorld, Mr_ch0c0late, Hahdrim
description=A mod that adds fancy armors from different cultures.
minecraft_version_range=[1.21, 1.22)
## This is the version of minecraft that the 'common' project uses, you can find a list of all versions here
## https://projects.neoforged.net/neoforged/neoform
neo_form_version=1.21.1-20240808.144430
# The version of ParchmentMC that is used, see https://parchmentmc.org/docs/getting-started#choose-a-version for new versions
parchment_minecraft=1.21.1
parchment_version=2024.11.17

yacl_version=3.7.1+1.21.1

# Fabric
## cf https://fabricmc.net/develop/ for last version
fabric_version=0.116.4+1.21.1
fabric_loader_version=0.16.14

# NeoForge
## cf https://projects.neoforged.net/neoforged/neoforge for last version
neoforge_version=21.1.197
neoforge_loader_version_range=[4,)

# Gradle
org.gradle.jvmargs=-Xmx8G
org.gradle.daemon=false
