modLoader="javafml"
loaderVersion="[36,)"
license="https://opensource.org/license/mit/"
issueTrackerURL="https://github.com/DawnOfTimeMC/armoroftheages/issues/"

[[mods]] #mandatory
    modId="armoroftheages"
    version="${file.jarVersion}"
    displayName="Armor of the Ages"
    displayURL="https://www.curseforge.com/minecraft/mc-mods/armor-of-the-ages"
    logoFile="logo.png"
    credits="Mr_ch0c0late, Hahdrim"
    authors="Poulpinou & TheGoldenWorld"
    description='''
    This mod adds many armor and weapons from different cultures.
    '''