plugins {
    id 'idea'
    id 'maven-publish'
    id 'net.neoforged.moddev.legacyforge'
}
base {
    archivesName = "${mod_name}-forge-${minecraft_version}"
}


mixin {
    add(sourceSets.main, "${mod_id}.refmap.json")

    config("${mod_id}.mixins.json")
    config("${mod_id}.forge.mixins.json")
}

repositories {
    maven {
        url "https://www.cursemaven.com"
        content {
            includeGroup "curse.maven"
        }
    }
}

legacyForge {
    version = "${minecraft_version}-${forge_version}"

    validateAccessTransformers = false

    def at = project(':common').file('src/main/resources/META-INF/accesstransformer.cfg')
    if (at.exists()) {
        accessTransformers = ["src/main/resources/META-INF/accesstransformer.cfg"]
    }

    parchment {
        minecraftVersion = parchment_minecraft
        mappingsVersion = parchment_version
    }

    runs {
        client {
            client()
        }
        data {
            data()
            programArguments.addAll '--mod', project.mod_id, '--all', '--output', file('src/generated/resources/').getAbsolutePath(), '--existing', file('src/main/resources/').getAbsolutePath()
        }
        server {
            server()
        }
    }

    mods {
        "${mod_id}" {
            sourceSet sourceSets.main
        }
    }
}

sourceSets.main.resources.srcDir 'src/generated/resources'

dependencies {
    implementation project(":common")

    annotationProcessor 'org.spongepowered:mixin:0.8.5:processor'
    implementation 'org.jetbrains:annotations:16.0.2'

    // Both numbers comes from Curse. The first number is the project_id (on the right) and the second one is the file_id (in the URL)
    modRuntimeOnly("curse.maven:jei-238222:5440261") // JEI (Just Enough Items)
    modRuntimeOnly("curse.maven:citadel-331936:5143956") // Citadel
    modRuntimeOnly("curse.maven:rats-323596:4802123") // Rats

    modImplementation("dev.isxander:yet-another-config-lib:${project.yacl_version}-forge")
}

compileTestJava.enabled = false

tasks.withType(JavaCompile).configureEach {
    source(project(":common").sourceSets.main.allSource)
}

tasks.named("sourcesJar", Jar) {
    from(project(":common").sourceSets.main.allSource)
}

processResources {
    from project(":common").sourceSets.main.resources
}

jar {
    finalizedBy('reobfJar')
    manifest.attributes([
            "MixinConfigs": "${mod_id}.mixins.json"
    ])
}


publishing {
    publications {
        mavenJava(MavenPublication) {
            artifactId base.archivesName.get()
            from components.java
        }
    }
    repositories {
        maven {
            url "file://" + System.getenv("local_maven")
        }
    }
}
