plugins {
    id 'idea'
    id 'java'
    id 'maven-publish'
    id 'fabric-loom'
}
base {
    archivesName = "${mod_name}-common-${minecraft_version}"
}

loom {
    if (project(":common").file("src/main/resources/${mod_id}.accesswidener").exists()) {
        accessWidenerPath.set(project(":common").file("src/main/resources/${mod_id}.accesswidener"))
    }
}

dependencies {
    minecraft "com.mojang:minecraft:${minecraft_version}"
    mappings loom.officialMojangMappings()

    implementation group: 'com.google.code.findbugs', name: 'jsr305', version: '3.0.1'

    modCompileOnly "net.fabricmc:fabric-loader:${fabric_loader_version}"
    modCompileOnly "dev.isxander:yet-another-config-lib:${project.yacl_version}-fabric"
}

publishing {
    publications {
        mavenJava(MavenPublication) {
            artifactId base.archivesName.get()
            from components.java
        }
    }
    repositories {
        maven {
            url "file://" + System.getenv("local_maven")
        }
    }
}