plugins {
    id 'multiloader-loader'
    id 'net.neoforged.moddev'
}

neoForge {
    version = neoforge_version
    // Automatically enable neoforge AccessTransformers if the file exists
    def at = project(':common').file('src/main/resources/META-INF/accesstransformer.cfg')
    if (at.exists()) {
        accessTransformers.add(at.absolutePath)
    }
    parchment {
        minecraftVersion = parchment_minecraft
        mappingsVersion = parchment_version
    }

    repositories {
        maven {
            url "https://www.cursemaven.com"
            content {
                includeGroup "curse.maven"
            }
        }
    }

    runs {
        configureEach {
            systemProperty('neoforge.enabledGameTestNamespaces', mod_id)
            ideName = "NeoForge ${it.name.capitalize()} (${project.path})" // Unify the run config names with fabric
        }
        client {
            client()
        }
        data {
            data()
            programArguments.addAll '--mod', mod_id, '--all', '--output', file('src/generated/resources/').absolutePath, '--existing', file('src/main/resources/').absolutePath
        }
        server {
            server()
        }
    }
    mods {
        "${mod_id}" {
            sourceSet sourceSets.main
        }
    }
}

sourceSets.main.resources { srcDir 'src/generated/resources' }

dependencies {
    // Both numbers comes from Curse. The first number is the project_id (on the right) and the second one is the file_id (in the URL)
    runtimeOnly "curse.maven:jei-238222:5466551" // JEI (Just Enough Items)
    //runtimeOnly "curse.maven:citadel-331936:5143956" // Citadel
    //runtimeOnly "curse.maven:rats-323596:4802123" // Rats

    implementation "thedarkcolour:kotlinforforge-neoforge:5.6.0"
    implementation ("dev.isxander:yet-another-config-lib:${project.yacl_version}-neoforge")
}